# Generated by Django 6.0.6 on 2026-07-14 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Name of the reviewing stakeholder.', max_length=100)),
                ('company_name', models.CharField(help_text='Company name representing the B2B client context.', max_length=150)),
                ('designation', models.CharField(help_text='Role or title of the stakeholder (e.g., CTO, Founder).', max_length=100)),
                ('client_avatar', models.ImageField(blank=True, help_text='Stakeholder portrait display asset.', null=True, upload_to='testimonials/avatars/')),
                ('review', models.TextField(help_text='The core testimonial statement narrative.', max_length=1000)),
                ('rating', models.PositiveIntegerField(default=5, help_text='Evaluated scale ranging from 1 to 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True, help_text='Controls inclusion metrics inside front-end slider loops.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ascending visual sorting priority.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, help_text='Optional completed case study linkage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Client Testimonial',
                'verbose_name_plural': 'Client Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
