# Generated by Django 6.0.6 on 2026-08-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_strip_demo_label_prefixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_sample',
            field=models.BooleanField(default=True, help_text='Marks this as a sample/demo review rather than a verified client testimonial. Sample reviews render a clearly labelled badge and are excluded from verified-client claims. Uncheck only once the review is a genuine, attributable client statement.'),
        ),
    ]
