# Generated by Django 6.0.6 on 2026-07-14 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Primary broadcast headline statement.', max_length=150)),
                ('content', models.TextField(help_text='Detailed broadcast parameters or update message.', max_length=2000)),
                ('target_role', models.CharField(choices=[('ALL', 'All Workspace Users'), ('CLIENT', 'Enterprise Clients Only'), ('DEVELOPER', 'Software Engineers Only'), ('MANAGER', 'Project Managers Only'), ('ADMIN', 'Administrators Only')], default='ALL', help_text='Filters target audience permission levels.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility thresholds on dashboard landing layouts.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The administrator who generated this announcement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace Announcement',
                'verbose_name_plural': 'Workspace Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
