# Generated by Django 6.0.6 on 2026-07-14 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ascending sort order priority.')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Website Development, AI Automation, Cyber Security.', max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Calculated automatically if left blank.', max_length=180, unique=True)),
                ('icon_class', models.CharField(default='fas fa-laptop-code', help_text="FontAwesome class icon tag representing this service (e.g., 'fas fa-brain').", max_length=100)),
                ('overview', models.TextField(help_text='Polished corporate summary statement.')),
                ('detailed_description', models.TextField(help_text='Detailed corporate summary block rendering rich HTML markup directly.')),
                ('features', models.TextField(help_text='List of core features. Enter one item per line.')),
                ('benefits', models.TextField(help_text='List of competitive benefits or outcomes. Enter one item per line.')),
                ('process_steps', models.TextField(help_text='Workflow steps. Enter one step per line in order.')),
                ('technologies', models.CharField(help_text='Comma-separated development environments and software (e.g. Django, Postgres, OpenAI).', max_length=255)),
                ('pricing_estimate', models.CharField(default='Starting from ₹29,999', help_text='Price range or starting rate placeholder statement.', max_length=150)),
                ('meta_title', models.CharField(blank=True, help_text='Enforces custom Title Tag override for search indexers.', max_length=150)),
                ('meta_description', models.TextField(blank=True, help_text='Enforces custom Meta Description override.', max_length=250)),
                ('is_active', models.BooleanField(default=True, help_text='Controls visual display metrics on public-facing page indexes.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(help_text='Select one or more categories associated with this corporate service.', related_name='services', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Corporate Solution',
                'verbose_name_plural': 'Corporate Solutions',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Ascending sort order priority.')),
                ('service', models.ForeignKey(help_text='The parent capability solution.', on_delete=django.db.models.deletion.CASCADE, related_name='service_faqs', to='services.service')),
            ],
            options={
                'verbose_name': 'Service FAQ',
                'verbose_name_plural': 'Service FAQs',
                'ordering': ['order', 'id'],
            },
        ),
    ]
