# Generated by Django 6.0.6 on 2026-07-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='pricing_estimate',
            field=models.CharField(default='Starting at ₹4,999', help_text='Price range or starting rate placeholder statement.', max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='e.g. Website Development, AI Automation, CRM Software Development.', max_length=150, unique=True),
        ),
    ]
