# Generated by Django 6.0.6 on 2026-07-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Primary stakeholder identity name.', max_length=100)),
                ('email', models.EmailField(help_text='Primary email for meeting notifications.', max_length=254)),
                ('phone', models.CharField(help_text='Standard contact telephone parameter.', max_length=20)),
                ('company', models.CharField(blank=True, help_text='Entity or company business name.', max_length=150)),
                ('industry', models.CharField(blank=True, help_text='e.g., E-commerce, Logistics, Healthcare, FinTech.', max_length=100)),
                ('budget', models.CharField(choices=[('under_1l', 'Less than ₹1,00,000'), ('1l_3l', '₹1,00,000 - ₹3,00,000'), ('3l_5l', '₹3,00,000 - ₹5,00,000'), ('over_5l', '₹5,00,000+')], help_text='Allocated project resource scale limits.', max_length=50)),
                ('services_required', models.CharField(choices=[('web_dev', 'Website Development'), ('app_dev', 'Web Application Development'), ('ai_automation', 'AI & WhatsApp Automation'), ('saas_erp', 'SaaS & CRM/ERP Development'), ('digital_marketing', 'SEO & Digital Marketing'), ('cloud_devops', 'Cloud & DevOps Solutions'), ('other', 'Custom Architectural Requirement')], help_text='Core service branch focus area.', max_length=100)),
                ('project_details', models.TextField(help_text='Detailed project requirements, current tech stack, or problem statement.', max_length=3000)),
                ('preferred_contact_time', models.CharField(choices=[('morning', 'Morning (10:00 AM - 1:00 PM IST)'), ('afternoon', 'Afternoon (1:00 PM - 5:00 PM IST)'), ('evening', 'Evening (5:00 PM - 8:00 PM IST)')], help_text='Target timezone allocation preference.', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Triage'), ('SCHEDULED', 'Meeting Scheduled'), ('COMPLETED', 'Consultation Completed'), ('CANCELLED', 'Client Cancelled')], default='PENDING', help_text='Current process phase in CRM workspace.', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='Confirmed meeting time mapping (Set by Admin).', null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Dynamic video-call coordinate (Zoom / Google Meet URL).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consultation Booking',
                'verbose_name_plural': 'Consultation Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
