# Generated by Django 6.0.6 on 2026-08-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='website_url',
            field=models.URLField(blank=True, help_text='Existing website URL to be reviewed as part of the free audit (optional if the business has no site yet).', max_length=255),
        ),
    ]
