# Generated by Django 6.0.6 on 2026-07-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Inquirer's identity name.", max_length=100)),
                ('email', models.EmailField(help_text="Inquirer's contact email address.", max_length=254)),
                ('phone', models.CharField(help_text='Standard contact telephone parameter.', max_length=20)),
                ('company', models.CharField(blank=True, help_text='Company or corporate context entity name.', max_length=150)),
                ('budget', models.CharField(choices=[('under_1l', 'Less than ₹1,00,000'), ('1l_3l', '₹1,00,000 - ₹3,00,000'), ('3l_5l', '₹3,00,000 - ₹5,00,000'), ('over_5l', '₹5,00,000+')], help_text='Allocated project resource scale limits.', max_length=50)),
                ('service', models.CharField(choices=[('web_dev', 'Website Development'), ('app_dev', 'Web Application Development'), ('ai_automation', 'AI & WhatsApp Automation'), ('saas_erp', 'SaaS & CRM/ERP Development'), ('digital_marketing', 'SEO & Digital Marketing'), ('cloud_devops', 'Cloud & DevOps Solutions'), ('other', 'Custom Architectural Requirement')], help_text='The target corporate solution requested.', max_length=100)),
                ('message', models.TextField(help_text='The core custom project scope statement.', max_length=2000)),
                ('is_processed', models.BooleanField(default=False, help_text='Designates whether sales teams have reviewed this lead.')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes during administrative processing.', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
