# Generated by Django 6.0.6 on 2026-09-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='budget',
            field=models.CharField(choices=[('30k_50k', '₹30,000 – ₹50,000'), ('50k_75k', '₹50,000 – ₹75,000'), ('75k_1l', '₹75,000 – ₹1,00,000'), ('1l_1_5l', '₹1,00,000 – ₹1,50,000'), ('1_5l_2l', '₹1,50,000 – ₹2,00,000'), ('2l_plus', '₹2,00,000+')], help_text='Allocated project resource scale limits.', max_length=50),
        ),
    ]
