# Generated by Django 6.0.6 on 2026-09-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmessage_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Submitting client IP (server-side abuse forensics; admin only).', null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='spam_reason',
            field=models.CharField(blank=True, default='', help_text='Why this lead carries the Spam status (empty for normal leads).', max_length=64),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processed', 'Processed'), ('spam', 'Spam')], db_index=True, default='new', help_text='Pipeline state: New, Processed, or Spam.', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Legacy mirror of status=Processed, kept for older queries.'),
        ),
        migrations.CreateModel(
            name='AbuseBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('email', 'Email address'), ('phone', 'Phone number'), ('ip', 'IP address')], help_text='Identifier type this entry blocks.', max_length=10)),
                ('value', models.CharField(help_text='Normalized identifier value (lowercase email / digits / canonical IP).', max_length=255)),
                ('reason', models.CharField(blank=True, default='', help_text='Internal justification recorded by staff.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive entries are retained for history but never match.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abuse Block',
                'verbose_name_plural': 'Abuse Blocks',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'value'), name='unique_abuse_block_identifier')],
            },
        ),
    ]
