# Generated by Django 6.0.6 on 2026-07-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'unique': 'This email address is already subscribed to our newsletter.'}, help_text='The target communication email channel.', max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp logging subscription registration.')),
                ('is_active', models.BooleanField(default=True, help_text='Enables administrative pause states for specific targets.')),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
