# Generated by Django 6.0.6 on 2026-07-14 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('featured_image', models.ImageField(help_text='Primary blog image asset.', upload_to='blog/featured/')),
                ('content', models.TextField(help_text='Markdown or rich HTML structured editorial copy.')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keyword tags.', max_length=255)),
                ('reading_time', models.PositiveIntegerField(blank=True, help_text='Calculated automatically based on content word count if empty.')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Simple read count indicator.')),
                ('is_published', models.BooleanField(default=False, help_text='Controls index eligibility on public feed screens.')),
                ('is_featured', models.BooleanField(default=False, help_text='Promotes article to high-level layout containers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Actual publishing trigger timestamp.', null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Enforces custom Title Tag override.', max_length=150)),
                ('meta_description', models.TextField(blank=True, help_text='Enforces custom Meta Description override.', max_length=250)),
                ('author', models.ForeignKey(help_text='Author profile managing verification and credentials.', on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Primary technical branch classification.', on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Publication',
                'verbose_name_plural': 'Blog Publications',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display identity name.', max_length=100)),
                ('email', models.EmailField(help_text='Primary email for tracking purposes.', max_length=254)),
                ('content', models.TextField(help_text='The core submitted statement text.', max_length=1000)),
                ('is_approved', models.BooleanField(default=False, help_text='Spam-prevention moderation validation status.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
