# Generated by Django 6.0.6 on 2026-07-14 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ascending sort order priority.')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The exact query or question statement.', max_length=255)),
                ('answer', models.TextField(help_text='The explanatory descriptive copy answer.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Priority ordering inside category accordion containers.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls visual display metrics on pages index accordions.')),
                ('category', models.ForeignKey(help_text='Primary grouping topic.', on_delete=django.db.models.deletion.PROTECT, related_name='faqs', to='faq.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ Accordion Item',
                'verbose_name_plural': 'FAQ Accordion Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
