# Generated by Django 6.0.6 on 2026-07-14 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('featured_image', models.ImageField(help_text='Primary visualization card banner.', upload_to='portfolio/featured/')),
                ('video_url', models.URLField(blank=True, help_text='Optional embedded link showing design or code demonstrations.', null=True)),
                ('client_name', models.CharField(help_text='Business or corporate name.', max_length=150)),
                ('industry', models.CharField(help_text='The corporate sector targeted.', max_length=100)),
                ('problem_statement', models.TextField(help_text='State of legacy structures or challenges solved.')),
                ('solution_statement', models.TextField(help_text='Detailed engineering architecture deployed by GrowthSpare.')),
                ('results_statement', models.TextField(help_text='Verified quantitative results (e.g., 200% scaling increase).')),
                ('technology_stack', models.CharField(help_text='Comma-separated development tools (e.g., Django, React, AWS).', max_length=255)),
                ('project_duration', models.CharField(help_text='Deployment timeline (e.g., 2 Months, 12 Weeks).', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated descriptive keyword tags.', max_length=255)),
                ('is_featured', models.BooleanField(default=False, help_text='Enables display in landing page showcase sections.')),
                ('meta_title', models.CharField(blank=True, help_text='Enforces custom Title Tag override.', max_length=150)),
                ('meta_description', models.TextField(blank=True, help_text='Enforces custom Meta Description override.', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(help_text='Select one or more categories associated with this showcase project.', related_name='projects', to='portfolio.projectcategory')),
            ],
            options={
                'verbose_name': 'Enterprise Case Study',
                'verbose_name_plural': 'Enterprise Case Studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Short label shown below image inside dynamic slider containers.', max_length=150)),
                ('project', models.ForeignKey(help_text='The associated case study parent model.', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Gallery Image',
                'verbose_name_plural': 'Project Gallery Images',
            },
        ),
    ]
