# Generated by Django 6.0.6 on 2026-08-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_concept_project',
            field=models.BooleanField(default=True, help_text="Marks this as a concept/demo project rather than a verified paid client engagement. Concept projects render a clearly labelled 'Concept Project' badge and omit unverified client/results claims from SEO structured data. Uncheck only once the client relationship and stated results are genuine and verifiable."),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.URLField(help_text='Primary visualization card banner URL.'),
        ),
    ]
