# Generated by Django 6.0.6 on 2026-08-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_is_concept_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Optional link to the live project website (e.g., https://example.com).', null=True),
        ),
    ]
